language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libyaml-cpp-dev libboost-dev # boost is needed as depend for libyaml-cpp, as ubuntu package misses needed dependency. See https://bugs.launchpad.net/ubuntu/+source/yaml-cpp/+bug/1318940
script:
  - cmake .
  - VERBOSE=1 make
  - make ARGS=-V test || true # some test intentionally fail for now
# - cppcheck -I . --enable=performance,portability,information,missingInclude --error-exitcode=2 SDL2pp # `style' gives false positive in cppcheck 1.61 which comes with trusty
