# - Try to locate yaml-cpp
# This module defines:
#
#  YAMLCPP_INCLUDE_DIRS
#  YAMLCPP_LIBRARIES
#  YAMLCPP_FOUND
#

FIND_PATH(YAMLCPP_INCLUDE_DIRS NAMES yaml-cpp/yaml.h)

FIND_LIBRARY(YAMLCPP_LIBRARIES NAMES yaml-cpp)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(YAMLCPP REQUIRED_VARS YAMLCPP_INCLUDE_DIRS YAMLCPP_LIBRARIES)

MARK_AS_ADVANCED(YAMLCPP_INCLUDE_DIRS YAMLCPP_LIBRARIES)
